name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Встановлення Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ви можете змінити версію Node.js на потрібну

      # Крок 3: Встановлення залежностей
      - name: Install dependencies
        run: npm install

      # Крок 4: Запуск тестів (наприклад, із Cypress)
      - name: Run Cypress tests
        run: npm run cy:run # Припускаю, що у вас є скрипт "cy:run" для запуску тестів у package.json
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Якщо ви використовуєте Cypress Dashboard

      # Крок 5 (опціонально): Збереження артефактів (наприклад, скріншоти з тестів)
      - name: Upload test artifacts
        if: failure() # Завантажуємо артефакти, якщо тести провалилися
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
