name: E2E on Chrome

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run:
    runs-on: ubuntu-latest
    name: E2E on Chrome

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: List AMAZON folder
        run: ls -R AMAZON

      - name: Install dependencies
        run: cd AMAZON && npm install

      - name: Run Cypress tests
        run: cd AMAZON && npx cypress run --browser chrome

      - name: Check for screenshots
        if: failure()
        run: ls -R AMAZON/cypress/screenshots || echo "No screenshots found"

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: AMAZON/cypress/screenshots
